config:
  partial_parse: true

nyc_taxi_green:
  target: fabric-dev
  outputs:
    fabric-dev:
      type: fabric
      authentication: CLI
      driver: "ODBC Driver 18 for SQL Server"
      host: "darotj3cokvunnehuukvqdnj7i-3k3f5vthqylujfs4ef2p73sxvm.datawarehouse.fabric.microsoft.com"
      database: "taxi"
      schema: "dbo"
      threads: 4